// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/greet/greet.proto

package com.proto.greet;

public interface GreetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.GreetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
