// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/greet/greet.proto

package com.proto.greet;

public interface GreetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.GreetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.greet.Greeting greeting = 1;</code>
   * @return Whether the greeting field is set.
   */
  boolean hasGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   * @return The greeting.
   */
  com.proto.greet.Greeting getGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   */
  com.proto.greet.GreetingOrBuilder getGreetingOrBuilder();
}
